### ISSUE TITLE
Implement dynamic loading of Tor Hidden Service Keys

### ISSUE THREAD

**Issue by fpietrosanti** [meejah/txtorcon#13]
Following the implementation of Tor's Ticket  https://trac.torproject.org/projects/tor/ticket/5976 this ticket is to implement proper txtorconn functionalities for:
- Loading a Tor Hidden Service Key via Tor CP
- Querying the Tor Hidden Service Hostname via Tor CP

This ticket is also referenced by https://github.com/globaleaks/APAF/issues/27

**Comment by david415** [comment]
I think this Tor Project ticket is related to this github issue:
https://trac.torproject.org/projects/tor/ticket/1949

**Comment by meejah** [comment]
Actually, see https://trac.torproject.org/projects/tor/ticket/6411 it seems there is other interest in this, and a patch in-progress to add controller commands to allow applications to directly add hidden-service keys they manage themselves.

There would be txtorcon work when 6411 is done: augmenting TorConfig to generate keys and use the new commands to add/remove these hidden services.

One open question would be whether it makes sense to have TorConfig.hiddenservices contain both "permanent" and "ephemeral" hidden services, or to have two lists...

**Comment by fpietrosanti** [comment]
@meejah I think that once the Tor-code to load with Tor CP is Ephemeral itself, TxTorCon shall provide ephemeral support for key too, leaving to the application logic the handling of the key material. 
What would be useful, for sure, is the support for the key generation in a "safe enough" way, so the application can just ask TxTorCon to generate a new key or to load an existing one previously generated.

**Comment by Yawning** [comment]
@fpietrosanti Hopefully generating RSA keys is well understood by this point.  The format the WIP code expects is just a Base64 string containing the PKCS#1 style DER encoded private key, which is fairly ubiquitous (It's the text that appears between "-----BEGIN RSA PRIVATE KEY-----" and "-----END RSA PRIVATE KEY-----" with the newlines stripped).  As I noted in the bug, there's sample code at https://github.com/yawning/orkey that does this correctly (though Go provides both RSA key generation and an ASN.1 DER encoder as part of the runtime).

Open design questions (some mirrored from the tor side bug, though if people are talking here, I might as well ask again):
 * "250 OK" is a bit terse as far as responses go.  Should the onion service address be provided as well?  (I'm somewhat inclined to think that this is an application problem, since the onion address is trivially derived from the private key).
 * Should the ephemeral services disapear on config reload (Eg: SIGHUP?).  The code in my branch will tear them all down, because that was the easiest thing to implement, but persisting them isn't much harder.
 * (Long term) Authenticated HSes should be supported, but won't be in the initial revision.  Someone should come up with a sane design for this (Tor bug 1949 indicates that people thought about this more than I have).

There's no particular rush from my side, since this missed the 0.2.6.x feature freeze date, and it will be a while before 0.2.7.x.

**Comment by meejah** [comment]
See branch https://github.com/meejah/txtorcon/tree/yawning-feature-6411 (yawning-feature-6411) which can be used along with @Yawning's branch for Tor's #6411 (https://trac.torproject.org/projects/tor/ticket/6411) to try all this out.

**Comment by fpietrosanti** [comment]
I am so happy! :-) we started looking at this issue in august 2012, with this branch released under Tor 0.2.7 it will finally become a reality! 
Tnx @meejah and @yawning !

**Comment by fpietrosanti** [comment]
@meejah has this feature been merged in txtorcon? As we're now finally considering using it in GlobaLeaks /cc @evilaliv3

**Comment by meejah** [comment]
Yes, you can pass keys directly to a new enough Tor with the `ADD_ONION` command via `EphemeralHiddenService` https://github.com/meejah/txtorcon/blob/master/txtorcon/torconfig.py#L906

The API will likely change slightly in 1.0 as I've unified all the various hidden-service options in that branch. But, nothing drastic.
