### ISSUE TITLE
all_routers disappearing after NEWCONSENSUS?

### ISSUE THREAD

**Issue by meejah** [meejah/txtorcon#203]
It seems in latest txtorcon that the all_routers list in `TorState` becomes empty after a NEWCONSENSUS. Needs investigation.

**Comment by meejah** [comment]
This does appear to be true, and I have a (small) fix but I still don't understand the actual problem exactly :/

**Comment by meejah** [comment]
Early-return problem in https://github.com/meejah/txtorcon/commit/f2a18c6c7da68df76112723d67de67c8c5a26fd0

**Comment by evilaliv3** [comment]
thank you @meejah for fixing this so proactively!

i was just about to open this ticket and fix with the same patch :)

a good suggestion for all users of previous versions is to use ```state.routers.values()``` instead of ```state.all_routers()```.

this in the real could be an alternative that you could evaluate instead of keeping an additional list, it has a minor overhead due to the .values() call at runtime but due to the size of the object is really a minor thing.
